# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/microservices
spring.datasource.username=root
#spring.datasource.password=password


# Eureka configuration for client connecting with Eureka server
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka

