# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/microservices
spring.datasource.username=root
#spring.datasource.password=password

# JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Eureka configuration for client connecting with Eureka server
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka

